### PR TITLE
feat: add community as part of the URL

### PR DESCRIPTION
**Pull request by tonivj5**
Resolve the community using the URL (anchor/fragment). At first load, if there's a community in the URL it opens it and move the map to its location.

For example, the URLs will look:
https://angular-communities.com/#ngManila
https://angular-communities.com/#Angular%20Málaga
https://angular-communities.com/#Angular%20Wrocław

Inspired by @zaldih

### CODE REVIEW

**Comment by Caballerog** [comment]
I think the% 20% character is not a good idea, we could normalize the path and add the dash to the name

**Comment by tonivj5** [comment]
> I think the %20 character is not a good idea, we could normalize the path and add the dash to the name

Yeah, I thought it, but it has a problem when you denormalize the path to get its name. For example:
|`original` | `normalized` | `denormalized`|
|-----------|--------------|----------------|
`Angular Málaga` | `Angular-Málaga` | `Angular Málaga`
`Angular-IL` | `Angular-IL` | `Angular IL`

Hmm, maybe other character? One that we can be 100% sure it isn't going to be used? Or an special character like:
https://angular-communities.com/#Angular·Málaga
https://angular-communities.com/#Angular¯Málaga

Hmm, maybe it's a bit tricky for avoid the encoded space

**Comment by tonivj5** [comment]
Maybe, other option could be normalize the key of each community (and it can't contain spaces or other special characters):
```json5
// communities.json
{
	"ngMalaga": { // instead of Angular Málaga
		"name": "Angular Málaga"
	}
}
```

**Comment by Caballerog** [comment]
After much thought, perhaps the best solution is the one you initially propose in your PR because we might have to be performing conversion operations that add complexity to the code so as not to obtain a great benefit.

**Comment by NyaGarcia** [comment]
Although not the prettiest option out there, the %20 is considered the standard for URL encoding... So I'd go with it. We always have the option of changing it in the future.

**Pull request merged**
